### PR TITLE
DarkMode: various dark-mode fixes

### PR DESCRIPTION
**Pull request by REJack**
I've update the website to reflect a clean dark mode 😃 

- fix landing pre bottom margin
- fix avatar subtitle color
- fix badge text color (cyan badge)
- fix table custom bg colors
- fix menu custom active bg color
- fix spotlight bg color
- fix steps border & bg color

Let me know if you want some screenshots to compare the before and after.

### CODE REVIEW

**Comment by robsontenorio** [comment]
Hey @REJack  Thanks for this!

But here a thing for the upcoming MRs: instead of adding `dark:***` variant , please just chose a better color that looks like nice on `light` and `dark` themes

So, we keep examples less "bloated".  Because the  intention here is just a quick showcase that is possible to use CSS classes on certain components.

**Comment by REJack** [comment]
You should then more use underline, text-color and so on instead of background colors, they usually doesn't fit in light and dark schemes. I fully understand the not to bloated examples part, with underline or text-color you also give the user the visible ability to change individual stuff.

**Comment by robsontenorio** [comment]
Thanks for the tip and your help!

I am on the "light mode team" and tackle  "dark mode stuff" doubles my work 😢

**Comment by REJack** [comment]
I'm more the "dark mode user", we can tackle that together 😄 if you want to ;) but daisyUI has a good light/dark handling out of the box.

**Pull request merged**
